[versions]
agrona = "2.0.1"
checkstyle = "10.21.2"
commons-codec = "1.15"
commons-lang3 = "3.8.1"
gradle = "8.12.1"
hamcrest = "3.0"
httpcore = "4.4.14"
jqwik = "1.9.2"
jmh = "1.37"
json = "20250107"
junit = "5.11.4"
mockito = "5.15.2"
plexus = "3.3.0"
shadow = "8.3.6"
versions = "0.52.0"

[libraries]
agrona = { group = "org.agrona", name = "agrona", version.ref = "agrona" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commons-codec" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
httpcore = { group = "org.apache.httpcomponents", name = "httpcore", version.ref = "httpcore" }
jqwik = { group = "net.jqwik", name = "jqwik", version.ref = "jqwik" }
json = { group = "org.json", name = "json", version.ref = "json" }
jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
plexus-utils = { group = "org.codehaus.plexus", name = "plexus-utils", version.ref = "plexus" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
